import { Role, RoleConfig, RoleContextValue } from "@/components/types/roles"
import { createContext } from "react"


export const ROLES: RoleConfig[] = [
  {
    id: "frontend",
    label: "Frontend Engineer",
    shortLabel: "Frontend",
    description: "React, Next.js, Design Systems, Performance",
    icon: "⚡",
    accentFrom: "from-cyan-400",
    accentTo: "to-purple-400",
    accentMid: "via-purple-400",
    badgeText: "Senior Frontend Engineer & Technical Lead",
    badgeDark: "dark:bg-cyan-500/10 dark:text-cyan-400 dark:border-cyan-500/20",
    badgeLight: "bg-cyan-100 text-cyan-700 border-cyan-200",
    borderDark: "dark:hover:border-cyan-500/50",
    borderLight: "hover:border-cyan-300",
    glowColor: "rgba(6, 182, 212, 0.3)",
    heroGradient: "from-cyan-400 via-purple-400 to-pink-400",
    heroGradient2: "from-purple-400 via-pink-400 to-orange-400",
    textColor: "cyan-400",
    darkTextColor: "cyan-600",
  },
  {
    id: "platform",
    label: "Platform Engineer",
    shortLabel: "Platform",
    description: "Node.js, NestJS, APIs, Service Architecture",
    icon: "🏗️",
    accentFrom: "from-violet-400",
    accentTo: "to-blue-400",
    accentMid: "via-indigo-400",
    badgeText: "Senior Product Platform Engineer",
    badgeDark: "dark:bg-violet-500/10 dark:text-violet-400 dark:border-violet-500/20",
    badgeLight: "bg-violet-100 text-violet-700 border-violet-200",
    borderDark: "dark:hover:border-violet-500/50",
    borderLight: "hover:border-violet-300",
    glowColor: "rgba(139, 92, 246, 0.25)",
    heroGradient: "from-violet-400 via-indigo-400 to-blue-400",
    heroGradient2: "from-blue-400 via-cyan-400 to-teal-400",
    textColor: "violet-400",
    darkTextColor: "violet-600",
  },
  {
    id: "em",
    label: "Engineering Manager",
    shortLabel: "Eng Manager",
    description: "Team Leadership, Delivery, Mentorship",
    icon: "👥",
    accentFrom: "from-emerald-400",
    accentTo: "to-cyan-400",
    accentMid: "via-cyan-400",
    badgeText: "Engineering Manager · Technical Lead",
    badgeDark: "dark:bg-emerald-500/10 dark:text-emerald-400 dark:border-emerald-500/20",
    badgeLight: "bg-emerald-100 text-emerald-700 border-emerald-200",
    borderDark: "dark:hover:border-emerald-500/50",
    borderLight: "hover:border-emerald-300",
    glowColor: "rgba(16, 185, 129, 0.2)",
    heroGradient: "from-emerald-400 via-cyan-400 to-blue-400",
    heroGradient2: "from-cyan-400 via-purple-400 to-pink-400",
    textColor: "emerald-400",
    darkTextColor: "emerald-600",
  },
  {
    id: "sa",
    label: "Solutions Architect",
    shortLabel: "Architect",
    description: "System Design, Full Stack, Platform Thinking",
    icon: "🔭",
    accentFrom: "from-indigo-400",
    accentTo: "to-violet-400",
    accentMid: "via-purple-400",
    badgeText: "Solutions Architect · Platform Engineer",
    badgeDark: "dark:bg-indigo-500/10 dark:text-indigo-400 dark:border-indigo-500/20",
    badgeLight: "bg-indigo-100 text-indigo-700 border-indigo-200",
    borderDark: "dark:hover:border-indigo-500/50",
    borderLight: "hover:border-indigo-300",
    glowColor: "rgba(99, 102, 241, 0.2)",
    heroGradient: "from-indigo-400 via-purple-400 to-violet-400",
    heroGradient2: "from-violet-400 via-pink-400 to-rose-400",
    textColor: "indigo-400",
    darkTextColor: "indigo-600",
  },
]

export const ROLE_MAP: Record<string, Role> = {
  frontend: "frontend",
  fe: "frontend",
  platform: "platform",
  pe: "platform",
  em: "em",
  manager: "em",
  sa: "sa",
  architect: "sa",
}

export const ROLE_STORAGE_KEY = "kn_preferred_role"

export const RoleContext = createContext<RoleContextValue>({
  role: "frontend",
  roleConfig: ROLES[0],
  setRole: () => {},
  isHydrated: false,
})
